# Numpy

In [2]:
import numpy as np 

# Creating Arrays

In [3]:
myList = [1,2,3]
x = np.array(myList)
x

array([1, 2, 3])

In [4]:
y = np.array([4,5,6])
y

array([4, 5, 6])

In [6]:
mult = x * y
mult

array([ 4, 10, 18])

In [12]:
n = np.arange(0, 30, 2)

In [8]:
y.shape

(3,)

In [10]:
z = np.array([[1,23,4],[1,2,3]])
z

array([[ 1, 23,  4],
       [ 1,  2,  3]])

In [11]:
z.shape

(2, 3)

In [13]:
n.reshape(3,5)

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28]])

In [16]:
n.reshape(3,5)

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28]])

In [17]:
a = np.linspace(0, 3, 12)

In [18]:
a

array([ 0.        ,  0.27272727,  0.54545455,  0.81818182,  1.09090909,
        1.36363636,  1.63636364,  1.90909091,  2.18181818,  2.45454545,
        2.72727273,  3.        ])

In [19]:
len(a)

12

In [20]:
dummy = np.array([[1,2],[1,2]])
len(dummy)

2

In [22]:
dummy.shape

(2, 2)

In [24]:
dummy.reshape(4,1)

array([[1],
       [2],
       [1],
       [2]])

In [35]:
var = np.ones([2,2,2])
var

array([[[ 1.,  1.],
        [ 1.,  1.]],

       [[ 1.,  1.],
        [ 1.,  1.]]])

In [38]:
len(var[0][0])

2

In [39]:
np.eye(1,2)

array([[ 1.,  0.]])

In [43]:
np.eye(4,4)

array([[ 1.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  1.]])

In [44]:
np.repeat([1,2,3], 3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

In [48]:
b = np.ones([3,3], int)
b

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [51]:
np.vstack([b, b*2])

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [2, 2, 2],
       [2, 2, 2],
       [2, 2, 2]])

In [52]:
np.hstack([b,b*2])

array([[1, 1, 1, 2, 2, 2],
       [1, 1, 1, 2, 2, 2],
       [1, 1, 1, 2, 2, 2]])

# Operations

## Element wise

In [53]:
x, y = np.array([1,2,3]), np.array([4,5,6])

In [54]:
x + y

array([5, 7, 9])

In [55]:
x * y

array([ 4, 10, 18])

In [56]:
x ** y

array([  1,  32, 729])

In [57]:
x.dot(y)

32

In [59]:
z = np.array([y, y**2])
z

array([[ 4,  5,  6],
       [16, 25, 36]])

In [60]:
x.reshape(3,1)

array([[1],
       [2],
       [3]])

In [64]:
z.T.shape

(3, 2)

In [65]:
z.dtype

dtype('int64')

In [66]:
z = z.astype('f')

In [67]:
z.dtype

dtype('float32')

In [68]:
a = np.array([1,2,3,4,5])

In [69]:
a.min()

1

In [70]:
a.max()

5

In [72]:
a.mean()

3.0

In [73]:
a.std()

1.4142135623730951

In [75]:
a.argmax()

4

# Indexing/Slicing

In [76]:
s = np.arange(14)

In [78]:
s ** 2

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144, 169])

In [79]:
s[2]

2

In [80]:
s[2:4]

array([2, 3])

In [81]:
s = np.arange(15)

In [82]:
s.reshape(3,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [83]:
s.shape

(15,)

In [84]:
s = s.reshape(3,5)

In [85]:
s.shape

(3, 5)

In [86]:
s[:2,:2]

array([[0, 1],
       [5, 6]])

In [91]:
s = np.vstack([s,s])
s

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [93]:
s[::2,::2] = 0

In [94]:
s

array([[ 0,  1,  0,  3,  0],
       [ 5,  6,  7,  8,  9],
       [ 0, 11,  0, 13,  0],
       [ 0,  1,  2,  3,  4],
       [ 0,  6,  0,  8,  0],
       [10, 11, 12, 13, 14]])

In [96]:
o = np.ones([2,2])

In [97]:
s[:2,:2] = o

In [98]:
s

array([[ 1,  1,  0,  3,  0],
       [ 1,  1,  7,  8,  9],
       [ 0, 11,  0, 13,  0],
       [ 0,  1,  2,  3,  4],
       [ 0,  6,  0,  8,  0],
       [10, 11, 12, 13, 14]])

In [99]:
s[s>4]

array([ 7,  8,  9, 11, 13,  6,  8, 10, 11, 12, 13, 14])

In [100]:
s[s>4] = 4

In [101]:
s

array([[1, 1, 0, 3, 0],
       [1, 1, 4, 4, 4],
       [0, 4, 0, 4, 0],
       [0, 1, 2, 3, 4],
       [0, 4, 0, 4, 0],
       [4, 4, 4, 4, 4]])

In [102]:
s[s==4] = 12

In [103]:
s

array([[ 1,  1,  0,  3,  0],
       [ 1,  1, 12, 12, 12],
       [ 0, 12,  0, 12,  0],
       [ 0,  1,  2,  3, 12],
       [ 0, 12,  0, 12,  0],
       [12, 12, 12, 12, 12]])

In [104]:
s[s==4]

array([], dtype=int64)

In [105]:
s[s>4]

array([12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12])

In [106]:
n = s[:3,:3]

In [107]:
n

array([[ 1,  1,  0],
       [ 1,  1, 12],
       [ 0, 12,  0]])

In [108]:
n[:] = 0

In [109]:
n

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [110]:
s

array([[ 0,  0,  0,  3,  0],
       [ 0,  0,  0, 12, 12],
       [ 0,  0,  0, 12,  0],
       [ 0,  1,  2,  3, 12],
       [ 0, 12,  0, 12,  0],
       [12, 12, 12, 12, 12]])

In [111]:
c = s.copy()

In [112]:
c

array([[ 0,  0,  0,  3,  0],
       [ 0,  0,  0, 12, 12],
       [ 0,  0,  0, 12,  0],
       [ 0,  1,  2,  3, 12],
       [ 0, 12,  0, 12,  0],
       [12, 12, 12, 12, 12]])

In [113]:
c[:] = 44

In [114]:
c

array([[44, 44, 44, 44, 44],
       [44, 44, 44, 44, 44],
       [44, 44, 44, 44, 44],
       [44, 44, 44, 44, 44],
       [44, 44, 44, 44, 44],
       [44, 44, 44, 44, 44]])

In [115]:
s

array([[ 0,  0,  0,  3,  0],
       [ 0,  0,  0, 12, 12],
       [ 0,  0,  0, 12,  0],
       [ 0,  1,  2,  3, 12],
       [ 0, 12,  0, 12,  0],
       [12, 12, 12, 12, 12]])

# Iterate 

In [117]:
test = np.random.randint(0,10, (3,4))

In [118]:
test

array([[5, 1, 2, 1],
       [2, 5, 5, 3],
       [0, 4, 8, 6]])

In [119]:
for r in test:
    print(r)

[5 1 2 1]
[2 5 5 3]
[0 4 8 6]


In [121]:
v = np.array(test[r][c] for r in range(len(test)) for c in range(len(test[0])))

In [122]:
v

array(<generator object <genexpr> at 0x1128ef8e0>, dtype=object)

In [123]:
test[r][c] for r in range(len(test)) for c in range(len(test[0]))

SyntaxError: invalid syntax (<ipython-input-123-9b4cbfe3433b>, line 1)

In [124]:
for i,r in enumerate(test):
    print(f'{i}: {r}')

0: [5 1 2 1]
1: [2 5 5 3]
2: [0 4 8 6]


In [125]:
t2 = test ** 2

In [138]:
zz =zip(test, t2)

In [130]:
for i in zz:
    print(i)

(array([5, 1, 2, 1]), array([25,  1,  4,  1]))
(array([2, 5, 5, 3]), array([ 4, 25, 25,  9]))
(array([0, 4, 8, 6]), array([ 0, 16, 64, 36]))


In [139]:
for x,y in zz:
    print (x,y)

[5 1 2 1] [25  1  4  1]
[2 5 5 3] [ 4 25 25  9]
[0 4 8 6] [ 0 16 64 36]


In [132]:
res

[]

In [133]:
for x,y in zz:
    print(x,y)